# Generated by Django 3.2.13 on 2022-05-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0005_alter_rental_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_history',
            name='date',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='rental_history',
            name='memberID',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='rental_history',
            name='model',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='rental_history',
            name='vehicle_id',
            field=models.CharField(max_length=35),
        ),
    ]
