# Generated by Django 3.2.13 on 2022-05-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0007_auto_20220510_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequent_User_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberID', models.CharField(max_length=35)),
                ('DrivingPlan', models.CharField(max_length=35)),
                ('NofReservations', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Location_Pref_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NofReservations', models.CharField(max_length=35)),
                ('TotalHours', models.CharField(max_length=35)),
                ('Location', models.CharField(max_length=55)),
                ('Month', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=35)),
                ('lateFeeRevenue', models.CharField(max_length=35)),
                ('vehicle_id', models.CharField(max_length=35)),
                ('ReservationRevenue', models.CharField(max_length=35)),
            ],
        ),
    ]
